BoxLayout:
    orientation: 'vertical'

    MDToolbar:
        title: "bottomnavbar"

    MDBottomNavigation:
        MDBottomNavigationItem:
            name: 'screen1'
            text: "Youtube"
            icon: 'youtube'

            MDLabel:
                text: "python"
                halign: 'center'

        MDBottomNavigationItem:
            name: 'screen2'
            text: "python"
            icon: 'language-python'

            MDLabel:
                text: "python"
                halign: 'center'

        MDBottomNavigationItem:
            name: 'screen3'
            text: "instagram"
            icon: 'instagram'

            MDLabel:
                text: "python"
                halign: 'center'
