<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width,root.height
        #space between the buttons
        spacing :50
        padding: 50

        Button:
            text : "Hello World"

        Button:
            text : "How are you"

        Button:
            text : "Good Bye"
            pos_hint: {'center_x':0.5}
            size_hint : (None,None)
            width: 200
            height:50