Screen:
    MDCard:
        size_hint: None,None
        size:300,400
        pos_hint: {"center_x":0.5,"center_y":0.5}
        elevation :10
        padding:25
        spacing : 25
        orientation : 'vertical'

        MDLabel:
            id:welcome
            text: "Welcome"
            font_size:32
            halign:'center'
            size_hint_y: None
            height:self.texture_size[1]
            padding_y:15

        MDTextFieldRound:
            id :user
            hint_text:"User Name"
            icon_right: "account"
            size_hint_x: None
            width:200
            font_size:20
            pos_hint: {"center_x":0.5,"center_y":0.5}

        MDTextFieldRound:
            id : password
            hint_text:"Password"
            icon_right: "eye-off"
            size_hint_x: None
            width:200
            font_size:20
            pos_hint: {"center_x":0.5,"center_y":0.5}
            password: True

        MDRoundFlatButton:
            text: "LOG IN"
            font_size:20
            pos_hint: {"center_x":0.5,"center_y":0.5}
            on_press : app.logger()

        MDRoundFlatButton:
            text: "Clear"
            font_size:20
            pos_hint: {"center_x":0.5,"center_y":0.5}
            on_press : app.clear()

        Widget:
            size_hint_y : None
            height :10
