MDBoxLayout:
    orientation: 'vertical'
    MDToolbar:
        title: "Top Toolbars"
        left_action_items:[["menu"]]
        right_action_items:[["dots-vertical"]]

    MDLabel:
        id:my_label
        text : "butons"
        halign: "center"

    MDBottomAppBar:
        MDToolbar:
            icon: 'git'
            title : "Menu"
            type: 'bottom'
            #mode: "free-end"
            mode: 'end'

            on_action_button: app.presser()


